/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class FrmProducto extends javax.swing.JFrame {

    /**
     * Creates new form FrmProducto
     */
    public FrmProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        lblID = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblProductCategory = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        tfProductDueDate = new javax.swing.JTextField();
        tfProductPrice = new javax.swing.JTextField();
        tfIDProduct = new javax.swing.JTextField();
        tfProductName = new javax.swing.JTextField();
        tfProductCategory = new javax.swing.JTextField();
        btnClearProduct = new javax.swing.JButton();
        btnSaveProduct = new javax.swing.JButton();
        btnEditProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de producto");

        lblID.setText("ID");

        lblProductName.setText("Nombre ");

        lblProductCategory.setText("Categoría ");

        jLabel2.setText("Precio");

        lblDueDate.setText("Fecha de vencimiento");

        tfProductDueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductDueDateActionPerformed(evt);
            }
        });

        tfIDProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDProductActionPerformed(evt);
            }
        });

        tfProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductCategoryActionPerformed(evt);
            }
        });

        btnClearProduct.setText("Limpiar");
        btnClearProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearProductActionPerformed(evt);
            }
        });

        btnSaveProduct.setText("Guardar");
        btnSaveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProductActionPerformed(evt);
            }
        });

        btnEditProduct.setText("Editar");
        btnEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductActionPerformed(evt);
            }
        });

        btnDeleteProduct.setText("Eliminar");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClearProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteProduct))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductCategory)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfProductCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(tfProductPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDueDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfProductDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addComponent(lblProductName))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIDProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(tfProductName))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(tfIDProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductName)
                    .addComponent(tfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductCategory)
                    .addComponent(tfProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDueDate)
                    .addComponent(tfProductDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearProduct)
                    .addComponent(btnSaveProduct)
                    .addComponent(btnEditProduct)
                    .addComponent(btnDeleteProduct))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProductDueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductDueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProductDueDateActionPerformed

    private void tfIDProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDProductActionPerformed

    private void tfProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProductCategoryActionPerformed

    private void btnClearProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearProductActionPerformed
        tfIDProduct.setText("");
        tfProductName.setText("");
        tfProductCategory.setText("");
        tfProductPrice.setText("");
        tfProductDueDate.setText("");
        tfIDProduct.requestFocus();
    }//GEN-LAST:event_btnClearProductActionPerformed

    private void btnSaveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProductActionPerformed
        if (tfIDProduct.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El ID del producto no puede quedar vacío",
                    "Registro de producto", JOptionPane.ERROR_MESSAGE);
            tfIDProduct.requestFocus();
            return;
        }
        if (tfProductName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El nombre del producto no puede quedar vacío",
                    "Registro de producto", JOptionPane.ERROR_MESSAGE);
            tfProductName.requestFocus();
            return;
        }
        if (tfProductCategory.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "La categoría del producto no puede quedar vacía",
                    "Registro de productos", JOptionPane.ERROR_MESSAGE);
            tfProductCategory.requestFocus();
            return;
        }
        if (tfProductPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El precio del producto no puede quedar vacío",
                    "Registro de productos", JOptionPane.ERROR_MESSAGE);
            tfProductPrice.requestFocus();
            return;
        }
        if (tfProductDueDate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de vencimiento no puede quedar vacía",
                    "Registro de productos", JOptionPane.ERROR_MESSAGE);
            tfProductDueDate.requestFocus();
            return;
        }
    }//GEN-LAST:event_btnSaveProductActionPerformed

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        if (tfIDProduct.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El ID del producto no puede quedar vacío",
                    "Registro de producto", JOptionPane.ERROR_MESSAGE);
            tfIDProduct.requestFocus();
            return;
        }
        if (tfProductName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El nombre del producto no puede quedar vacío",
                    "Registro de producto", JOptionPane.ERROR_MESSAGE);
            tfProductName.requestFocus();
            return;
        }
        if (tfProductCategory.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "La categoría del producto no puede quedar vacía",
                    "Registro de productos", JOptionPane.ERROR_MESSAGE);
            tfProductCategory.requestFocus();
            return;
        }
        if (tfProductPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El precio del producto no puede quedar vacío",
                    "Registro de productos", JOptionPane.ERROR_MESSAGE);
            tfProductPrice.requestFocus();
            return;
        }
        if (tfProductDueDate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de vencimiento no puede quedar vacía",
                    "Registro de productos", JOptionPane.ERROR_MESSAGE);
            tfProductDueDate.requestFocus();
            return;
        }
    }//GEN-LAST:event_btnEditProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        if (!tfIDProduct.getText().isEmpty()) {
            int op = JOptionPane.showConfirmDialog(this,
                    "¿Realmente desea eliminar?",
                    "Eliminar producto", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                JOptionPane.showMessageDialog(this, "Eliminado con éxito");
            } else if (op == 1) {
                JOptionPane.showMessageDialog(this, "No se ha eliminado");
            }
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnSaveProduct;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblProductCategory;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JTextField tfIDProduct;
    private javax.swing.JTextField tfProductCategory;
    private javax.swing.JTextField tfProductDueDate;
    private javax.swing.JTextField tfProductName;
    private javax.swing.JTextField tfProductPrice;
    // End of variables declaration//GEN-END:variables
}
